package app.entities;
// Generated 11-30-2018 03:17:57 PM by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int id;
     private String name;
     private Double price;

    public Product() {
    }

	
    public Product(int id) {
        this.id = id;
    }
    public Product(int id, String name, Double price) {
       this.id = id;
       this.name = name;
       this.price = price;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


